### ISSUE TITLE
3d: CSG

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-new-features-3.1#23]
Show how to use Constructive Solid Geometry with a concrete, useful example.

To be fair, I'm not sure when it's desirable compared to e.g. modeling in Blender, even for prototyping. It'd be worth asking fellow developers how they use the feature. Working with booleans, spin, loft, etc. is all much more convenient for me in a 3d package. Although I'm sure there are cases where it can be useful!

**Comment by guilhermehto** [comment]
I'll work on this :)

Regarding the question you brought up, for me it comes down to convenience. Even though I know how to use Blender, it's easier for me to stay in godot and mock levels. Plus with hot reload it also gives more advantages for you to stay inside the engine instead of using an outside program.

Also, we are considering that most devs would know how to use blender (or other 3d modeling software), which is not always the case.

**Comment by henriiquecampos** [comment]
There is also the convenience of making this in real time. I think there are some mechanics I can think of that this would fit. Can this be used to make the camera have a mesh representing its sight and when the character is behind some object, buildings for instance, this mesh would cut it allowing the player to view through the building? If so, this would be a good use case

**Comment by guilhermehto** [comment]
Video is done, I'll render it over night and upload tomorrow morning.
